# Generated by Django 4.1.7 on 2023-05-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profice_pic",
            new_name="profile_pic",
        ),
    ]
